/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i4 from './login/login.component.ngfactory';
import * as i5 from './payment/payment.component.ngfactory';
import * as i6 from './app.component.ngfactory';
import * as i7 from '@angular/common';
import * as i8 from '@angular/platform-browser';
import * as i9 from '@angular/material';
import * as i10 from '@angular/animations/browser';
import * as i11 from '@angular/platform-browser/animations';
import * as i12 from '@angular/forms';
import * as i13 from '@angular/http';
import * as i14 from '@angular/animations';
import * as i15 from '@angular/flex-layout/media-query/breakpoints/break-points-token';
import * as i16 from '@angular/flex-layout/media-query/breakpoints/break-points-provider';
import * as i17 from '@angular/flex-layout/media-query/breakpoints/break-point-registry';
import * as i18 from '@angular/flex-layout/media-query/match-media';
import * as i19 from '@angular/flex-layout/media-query/media-monitor';
import * as i20 from '@angular/flex-layout/media-query/media-monitor-provider';
import * as i21 from '@angular/flex-layout/media-query/observable-media';
import * as i22 from '@angular/flex-layout/media-query/observable-media-provider';
import * as i23 from '@angular/cdk';
import * as i24 from '@angular/router';
import * as i25 from './guard.service';
import * as i26 from '@angular/flex-layout/media-query/_module';
import * as i27 from '@angular/flex-layout/flexbox/_module';
import * as i28 from './login/login.component';
import * as i29 from './payment/payment.component';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdDialogContainerNgFactory,i3.MdDatepickerContentNgFactory,i3.TooltipComponentNgFactory,
              i3.MdSnackBarContainerNgFactory,i3.SimpleSnackBarNgFactory,i4.LoginComponentNgFactory,
              i5.PaymentComponentNgFactory,i6.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4352,i0.LOCALE_ID,'ua',([] as any[])),i0.ɵmpd(4608,
          i7.NgLocalization,i7.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,
          i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i8.DomSanitizer,
              i8.ɵe,[i7.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i8.DomSanitizer]),
          i0.ɵmpd(4608,i8.HAMMER_GESTURE_CONFIG,i9.GestureConfig,([] as any[])),i0.ɵmpd(5120,
              i8.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i8.ɵDomEventsPlugin(p0_0),new i8.ɵKeyEventsPlugin(p1_0),
                    new i8.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i7.DOCUMENT,i7.DOCUMENT,i7.DOCUMENT,i8.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i8.EventManager,i8.EventManager,[i8.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i8.ɵDomSharedStylesHost,i8.ɵDomSharedStylesHost,[i7.DOCUMENT]),
          i0.ɵmpd(4608,i8.ɵDomRendererFactory2,i8.ɵDomRendererFactory2,[i8.EventManager,
              i8.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i10.AnimationDriver,i11.ɵc,([] as any[])),
          i0.ɵmpd(5120,i10.ɵAnimationStyleNormalizer,i11.ɵd,([] as any[])),i0.ɵmpd(4608,
              i10.ɵAnimationEngine,i11.ɵb,[i10.AnimationDriver,i10.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i11.ɵe,[i8.ɵDomRendererFactory2,i10.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i8.ɵSharedStylesHost,(null as any),[i8.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i8.Meta,
              i8.Meta,[i7.DOCUMENT]),i0.ɵmpd(4608,i8.Title,i8.Title,[i7.DOCUMENT]),
          i0.ɵmpd(4608,i12.ɵi,i12.ɵi,([] as any[])),i0.ɵmpd(4608,i12.FormBuilder,i12.FormBuilder,
              ([] as any[])),i0.ɵmpd(4608,i13.BrowserXhr,i13.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i13.ResponseOptions,i13.BaseResponseOptions,([] as any[])),
          i0.ɵmpd(5120,i13.XSRFStrategy,i13.ɵb,([] as any[])),i0.ɵmpd(4608,i13.XHRBackend,
              i13.XHRBackend,[i13.BrowserXhr,i13.ResponseOptions,i13.XSRFStrategy]),
          i0.ɵmpd(4608,i13.RequestOptions,i13.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i13.Http,i13.ɵc,[i13.XHRBackend,i13.RequestOptions]),i0.ɵmpd(4608,i14.AnimationBuilder,
              i11.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),i0.ɵmpd(5120,i15.BREAKPOINTS,
              i16.DEFAULT_BREAKPOINTS_PROVIDER_FACTORY,([] as any[])),i0.ɵmpd(4608,
              i17.BreakPointRegistry,i17.BreakPointRegistry,[i15.BREAKPOINTS]),i0.ɵmpd(4608,
              i18.MatchMedia,i18.MatchMedia,[i0.NgZone]),i0.ɵmpd(5120,i19.MediaMonitor,
              i20.MEDIA_MONITOR_PROVIDER_FACTORY,[[3,i19.MediaMonitor],i17.BreakPointRegistry,
                  i18.MatchMedia]),i0.ɵmpd(5120,i21.ObservableMedia,i22.OBSERVABLE_MEDIA_PROVIDER_FACTORY,
              [[3,i21.ObservableMedia],i18.MatchMedia,i17.BreakPointRegistry]),i0.ɵmpd(6144,
              i23.DIR_DOCUMENT,(null as any),[i8.DOCUMENT]),i0.ɵmpd(4608,i23.Directionality,
              i23.Directionality,[[2,i23.DIR_DOCUMENT]]),i0.ɵmpd(4608,i23.Platform,
              i23.Platform,([] as any[])),i0.ɵmpd(5120,i9.ScrollDispatcher,i9.ɵe,[[3,
              i9.ScrollDispatcher],i0.NgZone,i23.Platform]),i0.ɵmpd(5120,i9.ViewportRuler,
              i9.ɵc,[[3,i9.ViewportRuler],i9.ScrollDispatcher]),i0.ɵmpd(4608,i9.ScrollStrategyOptions,
              i9.ScrollStrategyOptions,[i9.ScrollDispatcher,i9.ViewportRuler]),i0.ɵmpd(5120,
              i9.OverlayContainer,i9.ɵa,[[3,i9.OverlayContainer]]),i0.ɵmpd(4608,i9.ɵt,
              i9.ɵt,[i9.ViewportRuler]),i0.ɵmpd(4608,i9.Overlay,i9.Overlay,[i9.ScrollStrategyOptions,
              i9.OverlayContainer,i0.ComponentFactoryResolver,i9.ɵt,i0.ApplicationRef,
              i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i9.FocusOriginMonitor,i9.FOCUS_ORIGIN_MONITOR_PROVIDER_FACTORY,
              [[3,i9.FocusOriginMonitor],i0.NgZone,i23.Platform]),i0.ɵmpd(5120,i9.UniqueSelectionDispatcher,
              i9.ɵh,[[3,i9.UniqueSelectionDispatcher]]),i0.ɵmpd(4608,i23.MdMutationObserverFactory,
              i23.MdMutationObserverFactory,([] as any[])),i0.ɵmpd(4608,i23.InteractivityChecker,
              i23.InteractivityChecker,[i23.Platform]),i0.ɵmpd(4608,i23.FocusTrapFactory,
              i23.FocusTrapFactory,[i23.InteractivityChecker,i23.Platform,i0.NgZone]),
          i0.ɵmpd(5120,i23.LiveAnnouncer,i23.LIVE_ANNOUNCER_PROVIDER_FACTORY,[[3,i23.LiveAnnouncer],
              [2,i23.LIVE_ANNOUNCER_ELEMENT_TOKEN],i23.Platform]),i0.ɵmpd(4608,i9.MdDialog,
              i9.MdDialog,[i9.Overlay,i0.Injector,[2,i7.Location],[3,i9.MdDialog]]),
          i0.ɵmpd(4608,i9.MdDatepickerIntl,i9.MdDatepickerIntl,([] as any[])),i0.ɵmpd(5120,
              i9.MdIconRegistry,i9.ICON_REGISTRY_PROVIDER_FACTORY,[[3,i9.MdIconRegistry],
                  [2,i13.Http],i8.DomSanitizer]),i0.ɵmpd(4608,i9.ɵx,i9.ɵx,([] as any[])),
          i0.ɵmpd(4608,i9.MdSnackBar,i9.MdSnackBar,[i9.Overlay,i23.LiveAnnouncer,[3,
              i9.MdSnackBar]]),i0.ɵmpd(4608,i9.MdSortHeaderIntl,i9.MdSortHeaderIntl,
              ([] as any[])),i0.ɵmpd(5120,i24.ActivatedRoute,i24.ɵf,[i24.Router]),
          i0.ɵmpd(4608,i24.NoPreloading,i24.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i24.PreloadingStrategy,(null as any),[i24.NoPreloading]),i0.ɵmpd(135680,
              i24.RouterPreloader,i24.RouterPreloader,[i24.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i24.PreloadingStrategy]),i0.ɵmpd(4608,i24.PreloadAllModules,
              i24.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i24.ROUTER_INITIALIZER,
              i24.ɵi,[i24.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i24.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i25.GuardService,i25.GuardService,
              [i24.Router]),i0.ɵmpd(4608,i25.CanActivatePayment,i25.CanActivatePayment,
              [i25.GuardService]),i0.ɵmpd(512,i7.CommonModule,i7.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i8.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,
              () => {
                return [i24.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i24.ɵg,i24.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i8.ɵc(p0_0,p0_1),i24.ɵh(p1_0)];
              },[[2,i8.NgProbeToken],[2,i0.NgProbeToken],i24.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i8.BrowserModule,i8.BrowserModule,[[3,i8.BrowserModule]]),i0.ɵmpd(512,
              i12.ɵba,i12.ɵba,([] as any[])),i0.ɵmpd(512,i12.FormsModule,i12.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i12.ReactiveFormsModule,i12.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i13.HttpModule,i13.HttpModule,([] as any[])),
          i0.ɵmpd(512,i11.BrowserAnimationsModule,i11.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i26.MediaQueriesModule,i26.MediaQueriesModule,([] as any[])),
          i0.ɵmpd(512,i27.FlexLayoutModule,i27.FlexLayoutModule,([] as any[])),i0.ɵmpd(512,
              i9.CompatibilityModule,i9.CompatibilityModule,([] as any[])),i0.ɵmpd(512,
              i23.BidiModule,i23.BidiModule,([] as any[])),i0.ɵmpd(256,i9.MATERIAL_SANITY_CHECKS,
              true,([] as any[])),i0.ɵmpd(512,i9.MdCommonModule,i9.MdCommonModule,
              [[2,i8.DOCUMENT],[2,i9.MATERIAL_SANITY_CHECKS]]),i0.ɵmpd(512,i23.PlatformModule,
              i23.PlatformModule,([] as any[])),i0.ɵmpd(512,i9.ScrollDispatchModule,
              i9.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,i9.MdRippleModule,
              i9.MdRippleModule,([] as any[])),i0.ɵmpd(512,i9.MdSelectionModule,i9.MdSelectionModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdOptionModule,i9.MdOptionModule,([] as any[])),
          i0.ɵmpd(512,i23.PortalModule,i23.PortalModule,([] as any[])),i0.ɵmpd(512,
              i9.OverlayModule,i9.OverlayModule,([] as any[])),i0.ɵmpd(512,i9.MdAutocompleteModule,
              i9.MdAutocompleteModule,([] as any[])),i0.ɵmpd(512,i9.StyleModule,i9.StyleModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdButtonModule,i9.MdButtonModule,([] as any[])),
          i0.ɵmpd(512,i9.MdButtonToggleModule,i9.MdButtonToggleModule,([] as any[])),
          i0.ɵmpd(512,i9.MdCardModule,i9.MdCardModule,([] as any[])),i0.ɵmpd(512,i9.MdChipsModule,
              i9.MdChipsModule,([] as any[])),i0.ɵmpd(512,i23.ObserveContentModule,
              i23.ObserveContentModule,([] as any[])),i0.ɵmpd(512,i9.MdCheckboxModule,
              i9.MdCheckboxModule,([] as any[])),i0.ɵmpd(512,i23.A11yModule,i23.A11yModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdDialogModule,i9.MdDialogModule,([] as any[])),
          i0.ɵmpd(512,i9.MdDatepickerModule,i9.MdDatepickerModule,([] as any[])),i0.ɵmpd(512,
              i23.CdkTableModule,i23.CdkTableModule,([] as any[])),i0.ɵmpd(512,i9.MdTableModule,
              i9.MdTableModule,([] as any[])),i0.ɵmpd(512,i9.MdExpansionModule,i9.MdExpansionModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdLineModule,i9.MdLineModule,([] as any[])),
          i0.ɵmpd(512,i9.MdGridListModule,i9.MdGridListModule,([] as any[])),i0.ɵmpd(512,
              i9.MdIconModule,i9.MdIconModule,([] as any[])),i0.ɵmpd(512,i9.MdInputModule,
              i9.MdInputModule,([] as any[])),i0.ɵmpd(512,i9.MdListModule,i9.MdListModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdMenuModule,i9.MdMenuModule,([] as any[])),
          i0.ɵmpd(512,i9.MdSelectModule,i9.MdSelectModule,([] as any[])),i0.ɵmpd(512,
              i9.MdTooltipModule,i9.MdTooltipModule,([] as any[])),i0.ɵmpd(512,i9.MdPaginatorModule,
              i9.MdPaginatorModule,([] as any[])),i0.ɵmpd(512,i9.MdProgressBarModule,
              i9.MdProgressBarModule,([] as any[])),i0.ɵmpd(512,i9.MdProgressSpinnerModule,
              i9.MdProgressSpinnerModule,([] as any[])),i0.ɵmpd(512,i9.MdRadioModule,
              i9.MdRadioModule,([] as any[])),i0.ɵmpd(512,i9.MdSidenavModule,i9.MdSidenavModule,
              ([] as any[])),i0.ɵmpd(512,i9.MdSliderModule,i9.MdSliderModule,([] as any[])),
          i0.ɵmpd(512,i9.MdSlideToggleModule,i9.MdSlideToggleModule,([] as any[])),
          i0.ɵmpd(512,i9.MdSnackBarModule,i9.MdSnackBarModule,([] as any[])),i0.ɵmpd(512,
              i9.MdSortModule,i9.MdSortModule,([] as any[])),i0.ɵmpd(512,i9.MdTabsModule,
              i9.MdTabsModule,([] as any[])),i0.ɵmpd(512,i9.MdToolbarModule,i9.MdToolbarModule,
              ([] as any[])),i0.ɵmpd(512,i9.MaterialModule,i9.MaterialModule,([] as any[])),
          i0.ɵmpd(1024,i24.ɵa,i24.ɵd,[[3,i24.Router]]),i0.ɵmpd(512,i24.UrlSerializer,
              i24.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i24.ChildrenOutletContexts,
              i24.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i24.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i7.LocationStrategy,i24.ɵc,[i7.PlatformLocation,
              [2,i7.APP_BASE_HREF],i24.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i7.Location,
              i7.Location,[i7.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i24.ROUTES,
              () => {
                return [[{path:'login',component:i28.LoginComponent},{path:'payment',
                    component:i29.PaymentComponent,canActivate:[i25.CanActivatePayment]},
                    {path:'',redirectTo:'/login',pathMatch:'full'}]];
              },([] as any[])),i0.ɵmpd(1024,i24.Router,i24.ɵe,[i0.ApplicationRef,i24.UrlSerializer,
              i24.ChildrenOutletContexts,i7.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i24.ROUTES,i24.ROUTER_CONFIGURATION,[2,i24.UrlHandlingStrategy],
              [2,i24.RouteReuseStrategy]]),i0.ɵmpd(512,i24.RouterModule,i24.RouterModule,
              [[2,i24.ɵa],[2,i24.Router]]),i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),
          i0.ɵmpd(256,i0.TRANSLATIONS_FORMAT,'xlf',([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWF0aC9HSVQvanNleHBlcnQxL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21hdGgvR0lUL2pzZXhwZXJ0MS9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
