/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['form[_ngcontent-%COMP%] {\n    display: block;\n    margin: auto;\n    max-width: 480px;\n}\n.error[_ngcontent-%COMP%] {\n    color: red;\n    font-weight: bold;\n}\nspan[_ngcontent-%COMP%]   md-icon[_ngcontent-%COMP%] {\n    vertical-align: middle;\n}\n.card-date[_ngcontent-%COMP%] {\n    margin-top: 16px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWF0aC9HSVQvanNleHBlcnQxL3NyYy9hcHAvcGF5bWVudC9wYXltZW50LmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tYXRoL0dJVC9qc2V4cGVydDEvc3JjL2FwcC9wYXltZW50L3BheW1lbnQuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
